apiVersion: apps/v1
kind: Deployment
metadata:
    name: vat-calc
    labels:
	app: vat-calc
spec:
    replicas: 3
    selector:
	matchLabels:
	    app: vat-calc
    template:
	metadata:
	    labels:
		app: vat-calc
	spec:
	    containers:
	      - name: vat-calc
		image: nji2odyz/vat-calc:latest
		imagePullPolicy: Always
		resources:
		    requests:
			memory: "8Mi"
			cpu: "50m"
		    limits:
			memory: "16Mi"
			cpu: "100m"
		ports:
		  - containerPort: 80  
